services:
  User\Infrastructure\User\UserRepository:
    class: User\Infrastructure\User\UserRepository
    arguments:
      - '@doctrine.orm.entity_manager'

  Gym\Infrastructure\Station\StationRepository:
    class: Gym\Infrastructure\Station\StationRepository
    arguments:
      - '@doctrine.orm.entity_manager'

  Gym\Infrastructure\Exercise\ExerciseRepository:
    class: Gym\Infrastructure\Exercise\ExerciseRepository
    arguments:
      - '@doctrine.orm.entity_manager'

  Gym\Infrastructure\Training\TrainingRepository:
    class: Gym\Infrastructure\Training\TrainingRepository
    arguments:
      - '@doctrine.orm.entity_manager'
