services:
  App\Command\UploadFileHandler:
    class: App\Command\UploadFileHandler
    arguments:
      - '@slugger'
      - '%photo_allowed_mime%'
      - '%photos_directory%'
    tags:
      - { name: tactician.handler, command: App\Command\UploadFile, bus: command }

  User\Domain\Command\RegisterUserHandler:
    class: User\Domain\Command\RegisterUserHandler
    arguments:
      - '@security.user_password_hasher'
      - '@User\Domain\User\UserPersister'
    tags:
      - { name: tactician.handler, command: User\Domain\Command\RegisterUser, bus: command }

  Gym\Domain\Command\CreateTrainingHandler:
    class: Gym\Domain\Command\CreateTrainingHandler
    arguments:
      - '@Gym\Domain\Training\TrainingPersister'
    tags:
      - { name: tactician.handler, command: Gym\Domain\Command\CreateTraining, bus: command }

  Gym\Domain\Command\CreateExerciseHandler:
    class: Gym\Domain\Command\CreateExerciseHandler
    arguments:
      - '@Gym\Domain\Exercise\ExercisePersister'
    tags:
      - { name: tactician.handler, command: Gym\Domain\Command\CreateExercise, bus: command }

  Gym\Domain\Command\CreateExerciseToStationHandler:
    class: Gym\Domain\Command\CreateExerciseToStationHandler
    arguments:
      - '@Gym\Domain\ExerciseToStation\ExerciseToStationPersister'
    tags:
      - { name: tactician.handler, command: Gym\Domain\Command\CreateExerciseToStation, bus: command }

  Gym\Domain\Command\CreateExerciseToTrainingHandler:
    class: Gym\Domain\Command\CreateExerciseToTrainingHandler
    arguments:
      - '@Gym\Domain\ExerciseToTraining\ExerciseToTrainingPersister'
    tags:
      - { name: tactician.handler, command: Gym\Domain\Command\CreateExerciseToTraining, bus: command }

  Gym\Domain\Command\CreateStationHandler:
    class: Gym\Domain\Command\CreateStationHandler
    arguments:
      - '@Gym\Domain\Station\StationPersister'
    tags:
      - { name: tactician.handler, command: Gym\Domain\Command\CreateStation, bus: command }

  Gym\Domain\Command\CreateTagsHandler:
    class: Gym\Domain\Command\CreateTagsHandler
    arguments:
      - '@Gym\Domain\Tag\TagPersister'
    tags:
      - { name: tactician.handler, command: Gym\Domain\Command\CreateTags, bus: command }

  Gym\Domain\Command\DeleteTrainingHandler:
    class: Gym\Domain\Command\DeleteTrainingHandler
    arguments:
      - '@Gym\Domain\Training\TrainingPersister'
    tags:
      - { name: tactician.handler, command: Gym\Domain\Command\DeleteTraining, bus: command }

  Gym\Domain\Command\DeleteTagsHandler:
    class: Gym\Domain\Command\DeleteTagsHandler
    arguments:
      - '@Gym\Domain\Tag\TagPersister'
    tags:
      - { name: tactician.handler, command: Gym\Domain\Command\DeleteTags, bus: command }
