services:
  App\Controller\BaseController:
    class: App\Controller\BaseController
    arguments:
      - '@App\QueryBus\QueryBus'
      - '@App\CommandBus\CommandBus'

  App\Controller\IndexController:
    parent: App\Controller\BaseController
    calls:
      - [ setContainer, [ '@Psr\Container\ContainerInterface' ] ]
    tags: [ 'controller.service_arguments', 'container.service_subscriber' ]

  App\Controller\LoginController:
    parent: App\Controller\BaseController
    calls:
      - [ setContainer, [ '@Psr\Container\ContainerInterface' ] ]
    tags: [ 'controller.service_arguments', 'container.service_subscriber' ]

  App\Controller\RegisterController:
    parent: App\Controller\BaseController
    calls:
      - [ setContainer, [ '@Psr\Container\ContainerInterface' ] ]
    tags: [ 'controller.service_arguments', 'container.service_subscriber' ]
