services:
  User\Domain\User\UserPersister:
    alias: User\Infrastructure\User\UserPersister

  Gym\Domain\Training\TrainingPersister:
    alias: Gym\Infrastructure\Training\TrainingPersister

  Gym\Domain\Exercise\ExercisePersister:
    alias: Gym\Infrastructure\Exercise\ExercisePersister

  Gym\Domain\ExerciseToTraining\ExerciseToTrainingPersister:
    alias: Gym\Infrastructure\ExerciseToTraining\ExerciseToTrainingPersister

  Gym\Domain\Tag\TagPersister:
    alias: Gym\Infrastructure\Tag\TagPersister

  Gym\Domain\Station\StationPersister:
    alias: Gym\Infrastructure\Station\StationPersister

  Gym\Domain\ExerciseToStation\ExerciseToStationPersister:
    alias: Gym\Infrastructure\ExerciseToStation\ExerciseToStationPersister
