services:
  User\Domain\User\UserPersister:
    alias: User\Infrastructure\User\UserPersister

  Gym\Domain\Training\TrainingPersister:
    alias: Gym\Infrastructure\Training\TrainingPersister

  Gym\Domain\Exercise\ExercisePersister:
    alias: Gym\Infrastructure\Exercise\ExercisePersister