services:
  Gym\Domain\Query\GetStationsHandler:
    class: Gym\Domain\Query\GetStationsHandler
    arguments:
      - '@Gym\Domain\Station\StationRepository'
    tags:
      - { name: tactician.handler, command: Gym\Domain\Query\GetStations, bus: query }

  Gym\Domain\Query\GetStationHandler:
    class: Gym\Domain\Query\GetStationHandler
    arguments:
      - '@Gym\Domain\Station\StationRepository'
    tags:
      - { name: tactician.handler, command: Gym\Domain\Query\GetStation, bus: query }

  Gym\Domain\Query\GetExercisesHandler:
    class: Gym\Domain\Query\GetExercisesHandler
    arguments:
      - '@Gym\Domain\Exercise\ExerciseRepository'
    tags:
      - { name: tactician.handler, command: Gym\Domain\Query\GetExercises, bus: query }

  Gym\Domain\Query\GetTrainingsHandler:
    class: Gym\Domain\Query\GetTrainingsHandler
    arguments:
      - '@Gym\Domain\Training\TrainingRepository'
    tags:
      - { name: tactician.handler, command: Gym\Domain\Query\GetTrainings, bus: query }

  Gym\Domain\Query\GetTrainingInProgressHelperHandler:
    class: Gym\Domain\Query\GetTrainingInProgressHelperHandler
    arguments:
      - '@Gym\Domain\Training\TrainingRepository'
      - '@Gym\Domain\Tag\TagRepository'
      - '@Gym\Domain\Station\StationRepository'
      - '@Gym\Domain\Exercise\ExerciseRepository'
    tags:
      - { name: tactician.handler, command: Gym\Domain\Query\GetTrainingInProgressHelper, bus: query }
