services:
  Gym\Domain\Query\GetStationsForReadHandler:
    class: Gym\Domain\Query\GetStationsForReadHandler
    arguments:
      - '@Gym\Domain\Station\StationRepository'
    tags:
      - { name: tactician.handler, command: Gym\Domain\Query\GetStationsForRead, bus: query }

  Gym\Domain\Query\GetStationHandler:
    class: Gym\Domain\Query\GetStationHandler
    arguments:
      - '@Gym\Domain\Station\StationRepository'
    tags:
      - { name: tactician.handler, command: Gym\Domain\Query\GetStation, bus: query }

  Gym\Domain\Query\GetExercisesHandler:
    class: Gym\Domain\Query\GetExercisesHandler
    arguments:
      - '@Gym\Domain\Exercise\ExerciseRepository'
    tags:
      - { name: tactician.handler, command: Gym\Domain\Query\GetExercises, bus: query }

  Gym\Domain\Query\GetExerciseHandler:
    class: Gym\Domain\Query\GetExerciseHandler
    arguments:
      - '@Gym\Domain\Exercise\ExerciseRepository'
    tags:
      - { name: tactician.handler, command: Gym\Domain\Query\GetExercise, bus: query }

  Gym\Domain\Query\GetExerciseForReadHandler:
    class: Gym\Domain\Query\GetExerciseForReadHandler
    arguments:
      - '@Gym\Domain\Exercise\ExerciseRepository'
    tags:
      - { name: tactician.handler, command: Gym\Domain\Query\GetExerciseForRead, bus: query }

  Gym\Domain\Query\GetLiftedWeightsHandler:
    class: Gym\Domain\Query\GetLiftedWeightsHandler
    arguments:
      - '@Gym\Domain\LiftedWeight\LiftedWeightRepository'
    tags:
      - { name: tactician.handler, command: Gym\Domain\Query\GetLiftedWeights, bus: query }

  Gym\Domain\Query\GetLiftedWeightsForTrainingReadHandler:
    class: Gym\Domain\Query\GetLiftedWeightsForTrainingReadHandler
    arguments:
      - '@Gym\Domain\LiftedWeight\LiftedWeightRepository'
    tags:
      - { name: tactician.handler, command: Gym\Domain\Query\GetLiftedWeightsForTrainingRead, bus: query }

  Gym\Domain\Query\FindLastLiftedWeightHandler:
    class: Gym\Domain\Query\FindLastLiftedWeightHandler
    arguments:
      - '@Gym\Domain\LiftedWeight\LiftedWeightRepository'
    tags:
      - { name: tactician.handler, command: Gym\Domain\Query\FindLastLiftedWeight, bus: query }

  Gym\Domain\Query\GetLiftedKilogramsCountHandler:
    class: Gym\Domain\Query\GetLiftedKilogramsCountHandler
    arguments:
      - '@Gym\Domain\LiftedWeight\LiftedWeightRepository'
    tags:
      - { name: tactician.handler, command: Gym\Domain\Query\GetLiftedKilogramsCount, bus: query }

  Gym\Domain\Query\GetTrainingHandler:
    class: Gym\Domain\Query\GetTrainingHandler
    arguments:
      - '@Gym\Domain\Training\TrainingRepository'
    tags:
      - { name: tactician.handler, command: Gym\Domain\Query\GetTraining, bus: query }

  Gym\Domain\Query\GetTrainingsHandler:
    class: Gym\Domain\Query\GetTrainingsHandler
    arguments:
      - '@Gym\Domain\Training\TrainingRepository'
    tags:
      - { name: tactician.handler, command: Gym\Domain\Query\GetTrainings, bus: query }

  Gym\Domain\Query\GetMetricsHelperHandler:
    class: Gym\Domain\Query\GetMetricsHelperHandler
    arguments:
      - '@Gym\Domain\LiftedWeight\LiftedWeightRepository'
    tags:
      - { name: tactician.handler, command: Gym\Domain\Query\GetMetricsHelper, bus: query }

  Gym\Domain\Query\GetTrainingInProgressHelperHandler:
    class: Gym\Domain\Query\GetTrainingInProgressHelperHandler
    arguments:
      - '@Gym\Domain\Training\TrainingRepository'
      - '@Gym\Domain\Tag\TagRepository'
      - '@Gym\Domain\Station\StationRepository'
      - '@Gym\Domain\Exercise\ExerciseRepository'
      - '@Gym\Domain\LiftedWeight\LiftedWeightRepository'
    tags:
      - { name: tactician.handler, command: Gym\Domain\Query\GetTrainingInProgressHelper, bus: query }
