services:
  Gym\Domain\Query\GetStationsHandler:
    class: Gym\Domain\Query\GetStationsHandler
    arguments:
      - '@Gym\Domain\Station\StationRepository'
    tags:
      - { name: tactician.handler, command: Gym\Domain\Query\GetStations, bus: query }

  Gym\Domain\Query\GetStationHandler:
    class: Gym\Domain\Query\GetStationHandler
    arguments:
      - '@Gym\Domain\Station\StationRepository'
    tags:
      - { name: tactician.handler, command: Gym\Domain\Query\GetStation, bus: query }

  Gym\Domain\Query\GetExercisesHandler:
    class: Gym\Domain\Query\GetExercisesHandler
    arguments:
      - '@Gym\Domain\Exercise\ExerciseRepository'
    tags:
      - { name: tactician.handler, command: Gym\Domain\Query\GetExercises, bus: query }