services:
  User\Domain\User\UserRepository:
    alias: User\Infrastructure\User\UserRepository

  Gym\Domain\Station\StationRepository:
    alias: Gym\Infrastructure\Station\StationRepository

  Gym\Domain\Exercise\ExerciseRepository:
    alias: Gym\Infrastructure\Exercise\ExerciseRepository

  Gym\Domain\ExerciseToStation\ExerciseToStationRepository:
    alias: Gym\Infrastructure\ExerciseToStation\ExerciseToStationRepository

  Gym\Domain\Training\TrainingRepository:
    alias: Gym\Infrastructure\Training\TrainingRepository

  Gym\Domain\Tag\TagRepository:
    alias: Gym\Infrastructure\Tag\TagRepository

  Gym\Domain\LiftedWeight\LiftedWeightRepository:
    alias: Gym\Infrastructure\LiftedWeight\LiftedWeightRepository