services:
  User\Domain\User\UserRepository:
    alias: User\Infrastructure\User\UserRepository

  Gym\Domain\Station\StationRepository:
    alias: Gym\Infrastructure\Station\StationRepository

  Gym\Domain\Exercise\ExerciseRepository:
    alias: Gym\Infrastructure\Exercise\ExerciseRepository

  Gym\Domain\Training\TrainingRepository:
    alias: Gym\Infrastructure\Training\TrainingRepository