# index_controller
home:
    path: /
    controller: App\Controller\IndexController::index
    methods: [ GET ]

quill:
    path: /quill
    controller: App\Controller\IndexController::quill
    methods: [ POST ]

# login_controller
login:
    path: /login
    controller: App\Controller\LoginController::login
    methods: [ GET, POST ]

logout:
    path: /logout
    methods: [ GET ]

# register_controller
register:
    path: /register
    controller: App\Controller\RegisterController::register
    methods: [ GET, POST ]

register_info:
    path: /register/info
    controller: App\Controller\RegisterController::registerInfo
    methods: [ GET ]

# station_controller
station_list:
    path: /station/list
    controller: App\Controller\StationController::list
    methods: [ GET ]

station_create:
    path: /station/create
    controller: App\Controller\StationController::create
    methods: [ GET, POST ]

station_read:
    path: /station/{id}/read
    controller: App\Controller\StationController::read
    methods: [ GET ]

station_update:
    path: /station/{id}/update
    controller: App\Controller\StationController::update
    methods: [ GET, POST ]

station_delete:
    path: /station/{id}/delete
    controller: App\Controller\StationController::delete
    methods: [ GET ]

# training_controller
training_in_progress:
    path: /training/{id}/in-progress
    controller: App\Controller\TrainingController::inProgress
    methods: [ GET ]

training_list:
    path: /training/list
    controller: App\Controller\TrainingController::list
    methods: [ GET ]

training_create:
    path: /training/create
    controller: App\Controller\TrainingController::create
    methods: [ GET, POST ]

training_delete:
    path: /training/{id}/delete
    controller: App\Controller\TrainingController::delete
    methods: [ GET ]

# exercise_controller
exercise_list:
    path: /exercise/list
    controller: App\Controller\ExerciseController::list
    methods: [ GET ]

exercise_create:
    path: /exercise/create
    controller: App\Controller\ExerciseController::create
    methods: [ GET, POST ]

exercise_read:
    path: /exercise/{id}/read
    controller: App\Controller\ExerciseController::read
    methods: [ GET ]

exercise_update:
    path: /exercise/{id}/update
    controller: App\Controller\ExerciseController::update
    methods: [ GET, POST ]

exercise_delete:
    path: /exercise/{id}/delete
    controller: App\Controller\ExerciseController::delete
    methods: [ GET ]